//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWindowsForms.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int urunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urunAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urunMarkaField;
        
        private System.Nullable<short> urunKategoriField;
        
        private System.Nullable<decimal> urunFiyatField;
        
        private System.Nullable<byte> urunStokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int urunID {
            get {
                return this.urunIDField;
            }
            set {
                if ((this.urunIDField.Equals(value) != true)) {
                    this.urunIDField = value;
                    this.RaisePropertyChanged("urunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string urunAd {
            get {
                return this.urunAdField;
            }
            set {
                if ((object.ReferenceEquals(this.urunAdField, value) != true)) {
                    this.urunAdField = value;
                    this.RaisePropertyChanged("urunAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string urunMarka {
            get {
                return this.urunMarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.urunMarkaField, value) != true)) {
                    this.urunMarkaField = value;
                    this.RaisePropertyChanged("urunMarka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> urunKategori {
            get {
                return this.urunKategoriField;
            }
            set {
                if ((this.urunKategoriField.Equals(value) != true)) {
                    this.urunKategoriField = value;
                    this.RaisePropertyChanged("urunKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> urunFiyat {
            get {
                return this.urunFiyatField;
            }
            set {
                if ((this.urunFiyatField.Equals(value) != true)) {
                    this.urunFiyatField = value;
                    this.RaisePropertyChanged("urunFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<byte> urunStok {
            get {
                return this.urunStokField;
            }
            set {
                if ((this.urunStokField.Equals(value) != true)) {
                    this.urunStokField = value;
                    this.RaisePropertyChanged("urunStok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientWindowsForms.ProductServiceReference.HelloWorldResponse HelloWorld(ClientWindowsForms.ProductServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.HelloWorldResponse> HelloWorldAsync(ClientWindowsForms.ProductServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ProductListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductList", ReplyAction="*")]
        ClientWindowsForms.ProductServiceReference.ProductListResponse ProductList(ClientWindowsForms.ProductServiceReference.ProductListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductList", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ProductListAsync(ClientWindowsForms.ProductServiceReference.ProductListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForms.ProductServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientWindowsForms.ProductServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForms.ProductServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientWindowsForms.ProductServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductList", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForms.ProductServiceReference.ProductListRequestBody Body;
        
        public ProductListRequest() {
        }
        
        public ProductListRequest(ClientWindowsForms.ProductServiceReference.ProductListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProductListRequestBody {
        
        public ProductListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWindowsForms.ProductServiceReference.ProductListResponseBody Body;
        
        public ProductListResponse() {
        }
        
        public ProductListResponse(ClientWindowsForms.ProductServiceReference.ProductListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientWindowsForms.ProductServiceReference.ProductDTO> ProductListResult;
        
        public ProductListResponseBody() {
        }
        
        public ProductListResponseBody(System.Collections.Generic.List<ClientWindowsForms.ProductServiceReference.ProductDTO> ProductListResult) {
            this.ProductListResult = ProductListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : ClientWindowsForms.ProductServiceReference.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<ClientWindowsForms.ProductServiceReference.ProductServiceSoap>, ClientWindowsForms.ProductServiceReference.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWindowsForms.ProductServiceReference.HelloWorldResponse ClientWindowsForms.ProductServiceReference.ProductServiceSoap.HelloWorld(ClientWindowsForms.ProductServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientWindowsForms.ProductServiceReference.HelloWorldRequest inValue = new ClientWindowsForms.ProductServiceReference.HelloWorldRequest();
            inValue.Body = new ClientWindowsForms.ProductServiceReference.HelloWorldRequestBody();
            ClientWindowsForms.ProductServiceReference.HelloWorldResponse retVal = ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.HelloWorldResponse> ClientWindowsForms.ProductServiceReference.ProductServiceSoap.HelloWorldAsync(ClientWindowsForms.ProductServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ClientWindowsForms.ProductServiceReference.HelloWorldRequest inValue = new ClientWindowsForms.ProductServiceReference.HelloWorldRequest();
            inValue.Body = new ClientWindowsForms.ProductServiceReference.HelloWorldRequestBody();
            return ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWindowsForms.ProductServiceReference.ProductListResponse ClientWindowsForms.ProductServiceReference.ProductServiceSoap.ProductList(ClientWindowsForms.ProductServiceReference.ProductListRequest request) {
            return base.Channel.ProductList(request);
        }
        
        public System.Collections.Generic.List<ClientWindowsForms.ProductServiceReference.ProductDTO> ProductList() {
            ClientWindowsForms.ProductServiceReference.ProductListRequest inValue = new ClientWindowsForms.ProductServiceReference.ProductListRequest();
            inValue.Body = new ClientWindowsForms.ProductServiceReference.ProductListRequestBody();
            ClientWindowsForms.ProductServiceReference.ProductListResponse retVal = ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).ProductList(inValue);
            return retVal.Body.ProductListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ClientWindowsForms.ProductServiceReference.ProductServiceSoap.ProductListAsync(ClientWindowsForms.ProductServiceReference.ProductListRequest request) {
            return base.Channel.ProductListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ProductListAsync() {
            ClientWindowsForms.ProductServiceReference.ProductListRequest inValue = new ClientWindowsForms.ProductServiceReference.ProductListRequest();
            inValue.Body = new ClientWindowsForms.ProductServiceReference.ProductListRequestBody();
            return ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).ProductListAsync(inValue);
        }
    }
}
