//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWindowsForms.ProductServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ProductServiceReference.ProductServiceSoap")]
    public interface ProductServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HelloWorld", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        string HelloWorld();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HelloWorld", ReplyAction = "*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();

        // CODEGEN: Generating message contract since message ProductListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ProductList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        ClientWindowsForms.ProductServiceReference.ProductListResponse ProductList(ClientWindowsForms.ProductServiceReference.ProductListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ProductList", ReplyAction = "*")]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ProductListAsync(ClientWindowsForms.ProductServiceReference.ProductListRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Identification : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string userNameField;

        private string passwordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ProductDTO : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int urunIDField;

        private string urunAdField;

        private string urunMarkaField;

        private System.Nullable<short> urunKategoriField;

        private System.Nullable<decimal> urunFiyatField;

        private System.Nullable<byte> urunStokField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int urunID
        {
            get
            {
                return this.urunIDField;
            }
            set
            {
                this.urunIDField = value;
                this.RaisePropertyChanged("urunID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string urunAd
        {
            get
            {
                return this.urunAdField;
            }
            set
            {
                this.urunAdField = value;
                this.RaisePropertyChanged("urunAd");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string urunMarka
        {
            get
            {
                return this.urunMarkaField;
            }
            set
            {
                this.urunMarkaField = value;
                this.RaisePropertyChanged("urunMarka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public System.Nullable<short> urunKategori
        {
            get
            {
                return this.urunKategoriField;
            }
            set
            {
                this.urunKategoriField = value;
                this.RaisePropertyChanged("urunKategori");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public System.Nullable<decimal> urunFiyat
        {
            get
            {
                return this.urunFiyatField;
            }
            set
            {
                this.urunFiyatField = value;
                this.RaisePropertyChanged("urunFiyat");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public System.Nullable<byte> urunStok
        {
            get
            {
                return this.urunStokField;
            }
            set
            {
                this.urunStokField = value;
                this.RaisePropertyChanged("urunStok");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProductList", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProductListRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public ClientWindowsForms.ProductServiceReference.Identification Identification;

        public ProductListRequest()
        {
        }

        public ProductListRequest(ClientWindowsForms.ProductServiceReference.Identification Identification)
        {
            this.Identification = Identification;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProductListResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProductListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public ClientWindowsForms.ProductServiceReference.ProductDTO[] ProductListResult;

        public ProductListResponse()
        {
        }

        public ProductListResponse(ClientWindowsForms.ProductServiceReference.ProductDTO[] ProductListResult)
        {
            this.ProductListResult = ProductListResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : ClientWindowsForms.ProductServiceReference.ProductServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<ClientWindowsForms.ProductServiceReference.ProductServiceSoap>, ClientWindowsForms.ProductServiceReference.ProductServiceSoap
    {

        public ProductServiceSoapClient()
        {
        }

        public ProductServiceSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string HelloWorld()
        {
            return base.Channel.HelloWorld();
        }

        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWindowsForms.ProductServiceReference.ProductListResponse ClientWindowsForms.ProductServiceReference.ProductServiceSoap.ProductList(ClientWindowsForms.ProductServiceReference.ProductListRequest request)
        {
            return base.Channel.ProductList(request);
        }

        public ClientWindowsForms.ProductServiceReference.ProductDTO[] ProductList(ClientWindowsForms.ProductServiceReference.Identification Identification)
        {
            ClientWindowsForms.ProductServiceReference.ProductListRequest inValue = new ClientWindowsForms.ProductServiceReference.ProductListRequest();
            inValue.Identification = Identification;
            ClientWindowsForms.ProductServiceReference.ProductListResponse retVal = ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).ProductList(inValue);
            return retVal.ProductListResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ClientWindowsForms.ProductServiceReference.ProductServiceSoap.ProductListAsync(ClientWindowsForms.ProductServiceReference.ProductListRequest request)
        {
            return base.Channel.ProductListAsync(request);
        }

        public System.Threading.Tasks.Task<ClientWindowsForms.ProductServiceReference.ProductListResponse> ProductListAsync(ClientWindowsForms.ProductServiceReference.Identification Identification)
        {
            ClientWindowsForms.ProductServiceReference.ProductListRequest inValue = new ClientWindowsForms.ProductServiceReference.ProductListRequest();
            inValue.Identification = Identification;
            return ((ClientWindowsForms.ProductServiceReference.ProductServiceSoap)(this)).ProductListAsync(inValue);
        }
    }
}
