//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urunAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> urunFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int urunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> urunKategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urunMarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> urunStokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urunAd {
            get {
                return this.urunAdField;
            }
            set {
                if ((object.ReferenceEquals(this.urunAdField, value) != true)) {
                    this.urunAdField = value;
                    this.RaisePropertyChanged("urunAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> urunFiyat {
            get {
                return this.urunFiyatField;
            }
            set {
                if ((this.urunFiyatField.Equals(value) != true)) {
                    this.urunFiyatField = value;
                    this.RaisePropertyChanged("urunFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int urunID {
            get {
                return this.urunIDField;
            }
            set {
                if ((this.urunIDField.Equals(value) != true)) {
                    this.urunIDField = value;
                    this.RaisePropertyChanged("urunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> urunKategori {
            get {
                return this.urunKategoriField;
            }
            set {
                if ((this.urunKategoriField.Equals(value) != true)) {
                    this.urunKategoriField = value;
                    this.RaisePropertyChanged("urunKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urunMarka {
            get {
                return this.urunMarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.urunMarkaField, value) != true)) {
                    this.urunMarkaField = value;
                    this.RaisePropertyChanged("urunMarka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> urunStok {
            get {
                return this.urunStokField;
            }
            set {
                if ((this.urunStokField.Equals(value) != true)) {
                    this.urunStokField = value;
                    this.RaisePropertyChanged("urunStok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DoWork", ReplyAction="http://tempuri.org/IProductService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DoWork", ReplyAction="http://tempuri.org/IProductService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductList", ReplyAction="http://tempuri.org/IProductService/ProductListResponse")]
        WcfService.ProductServiceReference.ProductDTO[] ProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductList", ReplyAction="http://tempuri.org/IProductService/ProductListResponse")]
        System.Threading.Tasks.Task<WcfService.ProductServiceReference.ProductDTO[]> ProductListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : WcfService.ProductServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<WcfService.ProductServiceReference.IProductService>, WcfService.ProductServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public WcfService.ProductServiceReference.ProductDTO[] ProductList() {
            return base.Channel.ProductList();
        }
        
        public System.Threading.Tasks.Task<WcfService.ProductServiceReference.ProductDTO[]> ProductListAsync() {
            return base.Channel.ProductListAsync();
        }
    }
}
